apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-nfs-pvc1
  namespace: project-k8s
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 100Mi
