---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deploy
  namespace: project-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-instance1
        image: ramichlagou/nodejs-backend:1
        envFrom:
        - configMapRef:
            name: mysql-configmap
        - secretRef:
            name: mysql-secret
...
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service1
  namespace: project-k8s
spec:
  selector:
    app: nodejs
  ports:
    - protocol:   TCP
      port:       5000
      targetPort: 3000
      

...
