---
apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: mynfs
  provisioner: rancher.io/local-path
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
...