apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv1
  labels:
    name: mynfs1 # name can be anything
spec:
  storageClassName: nfs
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server  # ip addres of nfs server
    path: "/data-nfs" # path to directory
